#!/usr/bin/env ruby

# A sanity check to ensure that gem is functional after installing the package.

require 'asciidoctor'

puts Asciidoctor.render("= Asciidoctor\n\nI'm **alive**!", :header_footer => true, :compact => true)
