#!/usr/bin/env ruby

# A sanity check to ensure that gem is functional after installing the package.

require 'asciidoctor'

source = <<EOS
= Asciidoctor
Author Name

http://asciidoctor.org[Asciidoctor] is an _open source_ implementation of
http://asciidoc.org[AsciiDoc] in [red]*Ruby*.
EOS

puts Asciidoctor.render(source, :backend => :html5, :header_footer => true, :compact => true, :safe => :safe, :attributes => 'linkcss!')
